### ISSUE TITLE
Chat commands: add missing aliases

### ISSUE THREAD

**Issue by YvesW** [runelite/wiki#102]
Probably move 6 jad challenge above inferno, then put colosseum below inferno.
https://github.com/runelite/runelite/commit/beb29e7acefda653c83377df3bdf589cc0e0055b

Also check other chat commands commits like https://github.com/runelite/runelite/commit/13e18d58fe0349b77d2c87bbc1dbc7ccc3e81986

**Comment by Felanbird** [comment]
bf33912cd603877a6a20b5936019c8f7708bf1f9 & 7c631c79b0332d178ef583c05366f7426d0b6463 for sol and hunter rumours

**Comment by YvesW** [comment]
Looking at the commit history of the chat commands plugin (https://github.com/runelite/runelite/commits/master/runelite-client/src/main/java/net/runelite/client/plugins/chatcommands), that should be all since my last chat-commands page revamp.
