### ISSUE TITLE
Add spellbook plugin to sidebar

### ISSUE THREAD

**Issue by YvesW** [runelite/wiki#104]
Right now the page is ~~completely~~ missing from the sidebar.

**Comment by Felanbird** [comment]
https://github.com/runelite/runelite/wiki/Spellbook

**Comment by Felanbird** [comment]
i didn't put it on the sidebar because idk, didn't feel like it

**Comment by YvesW** [comment]
Ah, I missed it because of that (and I'm on mobile rn). I'll change it to adding it to the sidebar.

**Comment by Felanbird** [comment]
6e20d01ff6e89a789bee44802c3db397d96708b0
