### ISSUE TITLE
Document the ability to disable hardware acceleration with `Runelite (configuration)`

### ISSUE THREAD

**Issue by Felanbird** [runelite/wiki#20]
In https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration - a few methods are listed for disabling Hardware acceleration, but there is not a method to easily disable it with the new `Runelite (configuration)` shortcut.

This approach should be added.

**Comment by Alexsuperfly** [comment]
added in e4159e3e70b67331867bab99e882546ea78c031d
