### ISSUE TITLE
Document the development issue where the client is see-through

### ISSUE THREAD

**Issue by Felanbird** [runelite/wiki#23]
During the setup process to build the client with Intellij, for an unknown reason, running the maven command once will start-up the client, but said client will be see-through, running maven again resolves this issue.

The ability to resolve this issue is technically documented [here:](https://github.com/runelite/wiki/blob/master/Building-with-IntelliJ-IDEA.md#client-failing-to-start--client-stuck-while-loading--client-crashes-while-playing) 
![image](https://user-images.githubusercontent.com/41973452/233728163-adc01835-511f-4dbf-bc3c-e7a697cffa0d.png)

but it doesn't _actually_ indicate it would resolve this issue specifically.

Personally I obviously had this issue when building the client, and only figured out the command would fix it due to me trying the command _just because_ it was there, and it just happened to work perfectly.

Apparently there is an explicit error for this issue, but I had never seen it nor was it in the screenshot posted by a user in the discord with said issue.

![image](https://user-images.githubusercontent.com/41973452/233726362-97578e2e-0ad7-476d-838d-c28f90791d93.png)

**Comment by Nightfirecat** [comment]
Do we know whether this is an issue that happens for users who actually run the install lifecycle before running the client? I think a good handful of people who get that error may not have followed the entire project building section before skipping ahead, in which case I don't think any change is needed.

**Comment by Felanbird** [comment]
As far as I remember, I believe I followed the instructions exactly as they were outlined, and ran into the issue once I was at `Running the project`, but it's totally possible that I skipped.

In most cases telling the user `run maven again` is good enough, but I don't see the harm in explaining a common mistake, if that's what it ends up being.

Also I just stole this documentation idea from adam so blame him
![image](https://user-images.githubusercontent.com/41973452/233737734-94233ceb-b5d2-4ea8-b4cf-cbfed0804b43.png)
