### ISSUE TITLE
Update Rejected feature page permitting use of Twitch emotes

### ISSUE THREAD

**Issue by binury** [runelite/wiki#66]
https://github.com/runelite/wiki/blob/d9b33c340e41106dd063c60d35de9b5bb3e018c2/Rejected-or-Rolled-Back-Features.md?plain=1#L31

In [an original PR to add a plugin to support](https://github.com/runelite/plugin-hub/pull/43) emote images, **there was  some uncertainty** and a brief comment chain about the legality of incorporating external assets which led to inaction[^0]… and it was never resolved or answered. And so for organizational purposes (?) the PR was closed **while awaiting communication**. No follow up was ever made on the PR and it stayed pending indefinitely closed. (But not rejected)

Contributors later submitting their own versions of the same feat. are **rejected by members who cite the original PR's (legal) uncertainty as _their own certain proof_** that similar PRs could not be merged.

And then this happens five or so more times and everyone seems **very very certain about something that was never resolved in the first place.**

I'm sure there might have been a resolution but looking over all the issues and PRs, there is no documentation of it. There is not even off-repo discussion referenced anywhere except within the original PR. ¯\\\_(ツ)_/¯ 
on the off chance there was not… you'll agree surely that one years-old timed-out PR is objectively not-great justification for giving up on implementing future contributions.

[^0]: (the PR was initially approved and then backtracked before merge due to [some offline discussion])

**Comment by binury** [comment]
@Nightfirecat Do you remember if the communication ever resolved or did this decision maybe happen through default?

**Comment by Nightfirecat** [comment]
We had further discussion in Discord mainly, and the conclusion we came to was, signs point to this not being something we can legally distribute, and there is no evidence that we would be able to do this. I don't recall of us finding anything conclusive one way or another, but that our intuition is that we don't want to do this.

**Comment by Felanbird** [comment]
I think you're drastically missing the point in your arguments.

> No follow up was ever made on the PR and it stayed pending indefinitely closed. (But not rejected)

It was definitely rejected, it's just that in some cases back then, updating the Rejected features page often fell through the cracks, and going back to a 2019/2020 PR and randomly saying "hey we officially came to the conclusion that this already closed PR, isn't getting merged" isn't something people feel necessary to do.

> you'll agree surely that one years-old timed-out PR is objectively not-great justification for giving up on implementing future contributions.

That's not what's happening, it's been rejected 7 times, it's very clear it's not going to be accepted, but now instead of people getting told after they've done the work, they now correctly know before they start.

While it is true the information around Twitch's part of this is spotty, it's not spotty for BTTV/FFZ/7TV, which all state they aren't to blame if an emote turns out to be copyrighted, it falls to the uploader, which means it falls to us if someone is upset that a plugin author stole and packaged their emote in a plugin.

It doesn't take much thinking to realize if the information for something is spotty, you don't want to mess around with it. 
Also the fact that their 3rd party emote services explicitly state they don't want the blame for this, tells us that we don't want the blame either.

**Comment by binury** [comment]
@Felanbird I'm not sure why you felt the need to leave a combative reply betrayed by lazily veiled condescension… considering the unwarranted disrespect, I definitely don't get the impression we are both willing to have adult communication in good faith… but I promise that was the initial intention on my part.
I'll try to be very direct and clearer now so that you might find the "points in my arguments" this time.


The original PR code doesn't exist for us to read anymore because. So, it's unclear to us e.g., _how_ was the feature being implemented?[^0]
There are -generally speaking- many pieces of history missing surrounding this particular feature and how it has been handled. Pieces that are -again- being reused over and over as citations for historical precedent in rejecting PRs and closing issues– like you haved closed this one mere hours after I opened it[^3]


Let's look at the first time this happened afterwards, if you haven't already:
A year afterwards, [another PR was submitted](https://github.com/runelite/plugin-hub/pull/1158) and luckily this time we can still access the repository source- where we'll see that there are _no images[^1] being bundled with the plugin_— and that it is making AJAX calls to the provider's APIs as-needed[^2].
This PR might have needed to remove endpoints that were not public APIs or unwilling to allow access, but there were no emotes in their plugin.


After this one– _three_ more PRs that imagine were closed because they share a similar title with the original issue. But they have all been deleted and so we can't re-review them now, anymore. and, no, there are no clues within their comments which are usually just containing anchors back to previous PRs. Bummer.


I'll stop here, as I think this alone is a good enough point for your consideration. and I hope you can see what I am getting at now. I'm not arguing against the reasons of the decisions, I am merely pointing out that the reasons were maybe in error- or are, at the least, no longer preventing the feature's inclusion.


[Twitch (Global) Emote API](https://discuss.dev.twitch.com/t/announcing-api-endpoints-for-twitch-emotes/32073)
 
 [^0]: The plugin is only referenced in an external repository which has been deleted. It's discussed with the term 'distributed' so one might imagine the images were going to be bundled in the client. And that was the licensing concern. Okay, let's assume that it was.
 [^1]:  apart from what looks like a test placeholder emote leftover in the repo
 [^2]: Of course it is!
[^3]: including all future issues, now: "won't be accepted."

**Comment by Nightfirecat** [comment]
The Twitch channel/global emote API does imply that there could be permissible use outside of the platform. I expect that other emote services (FFZ/BTTV/7TV) will not be something we can support per @Felanbird's comment, but I haven't seen this API offering from Twitch before, so I'll do some research and get back to you on this.

**Comment by Nightfirecat** [comment]
My read of Twitch's API docs seems to indicate that use of global or channel emotes is permissible so long as emote data is fetched via the API and downloaded from their CDN, ala https://dev.twitch.tv/docs/irc/emotes/

Given that, I'm willing to relax our position to permit usage of Twitch emotes so long as they follow that pattern, and welcome an update to [the Rejected or Rolled Back Features page](https://github.com/runelite/wiki/blob/3ead34d7494c5e7778fedb69be982e2d9bf3ad39/Rejected-or-Rolled-Back-Features.md?plain=1#L31) in kind--so long as that update also relays this directive.
