### ISSUE TITLE
Chainmace Animation Smoothing glitch

### ISSUE THREAD

**Issue by Dream3rz** [runelite/wiki#99]
There's a glitch right now where if you have Ursine Chain mace it randomly swings around with animation smoothing on. Even with 117HD off it still does it.

**Comment by YvesW** [comment]
This is the RuneLite **wiki** repo. You can report this on the runelite/runelite repo, if an issue does not exist yet. I'd also recommend attaching a video of it happening in safe mode with the title bar visible in that case.
